In [1]:
from array import *
p = array('i',[1,2,3,4,5,6])
def searchlinear(t,val):
    for i in t:   #............o(n)
        if i == val:       #............o(1)
            return t.index(val)
    return "no such element"
print(searchlinear(p,5))   #........sc = O(1) and TC =O(n)  

4


In [2]:
#delete frm array
p.remove(2)
print(p)

array('i', [1, 3, 4, 5, 6])


In [3]:
# 1. create an array and traverse
my_array = array('i',[1,2,3,4,5])

for i in my_array:
    print(i)            #O(n)

1
2
3
4
5


In [4]:
#2. Accessing element
print(my_array[2])

3


In [5]:
#3. append value
my_array.append(6)

print(my_array)

array('i', [1, 2, 3, 4, 5, 6])


In [6]:
#4. insert value

my_array.insert(0,11)
print(my_array)

array('i', [11, 1, 2, 3, 4, 5, 6])


In [7]:
# 5.extend `array
my_array2 =array('i',[10,11,12])
my_array.extend(my_array2)
print(my_array)

array('i', [11, 1, 2, 3, 4, 5, 6, 10, 11, 12])


In [8]:
#add items from list to array 
templist = [20,21,22]
my_array.fromlist(templist)
print(my_array)

array('i', [11, 1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22])


In [9]:
# 7. remove element
my_array.remove(11)

In [10]:
#8 remove last element
my_array.pop()
print(my_array)

array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21])


In [11]:
#9 fetch element index 
print(my_array.index(20))

9


In [12]:
#10 reverse 
my_array.reverse()
print(my_array)

array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1])


In [13]:
#11. buffer info
print(my_array.buffer_info())

(2612876755568, 11)


In [14]:
#12. count
print(my_array.count(11))

1


In [15]:
#13. convert array to string
strTemp = my_array.tostring()
print(strTemp)
ints = array('i')
ints.fromstring(strTemp)
print(ints)

b'\x15\x00\x00\x00\x14\x00\x00\x00\x0c\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00'
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1])


In [16]:
#14 convert to list
print(my_array.tolist())

[21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1]


In [17]:
# 15 slice
my_array[1:4]

array('i', [20, 12, 11])

In [18]:
import numpy as np
twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [19]:
newTwoArray = np.insert(twoDArray,0,[[1,2,3,4]],axis =1)# axis=1 column
print(newTwoArray)
    

[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


In [20]:
def traversearr(array):
    for i in range(len(array)):
        for  j in range(len(array[0])):
            print(array[i][j])
traversearr(twoDArray)           

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [23]:
def search(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return "the value found " + str(i)+str(j)
    return "element not found"        

In [24]:
search(twoDArray,10)

'the value found 02'

In [25]:
m = np.delete(twoDArray,0,axis =1)
m

array([[15, 10,  6],
       [14, 11,  5],
       [17, 12,  8],
       [18, 14,  9]])

In [26]:
a=[1,2,3,4,5]
print(a[3:0:-1])

[4, 3, 2]


In [28]:
a=[1,2,3,4,5,6,7,8,9]
a[::2]=10,20,30,40,50
print(a)

[10, 2, 20, 4, 30, 6, 40, 8, 50]


In [29]:
def f(i, values = []):
    values.append(i)
    print (values)
    return values
f(1)
f(2)
f(3)

[1]
[1, 2]
[1, 2, 3]


[1, 2, 3]

In [30]:
fruit_list1 = ['Apple', 'Berry', 'Cherry', 'Papaya']
fruit_list2 = fruit_list1
fruit_list3 = fruit_list1[:]
 
fruit_list2[0] = 'Guava'
fruit_list3[1] = 'Kiwi'
 
sum1 = 0
for ls in (fruit_list1, fruit_list2, fruit_list3):
    if ls[0] == 'Guava':
        sum1 += 1
    if ls[1] == 'Kiwi':
        sum1 += 20

In [31]:
sum1

22

In [32]:
def f(value, values):
    v = 1
    values[0] = 44
t = 3
v = [1, 2, 3]
f(t, v)
print(t, v[0])

3 44


In [33]:
data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
def fun(m):
    v = m[0][0]
 
    for row in m:
        for element in row:
            if v < element: v = element
 
    return v
print(fun(data[0]))

4


In [35]:
numDays = int(input("how many day's temp? "))
total = 0
temp = []
for i in range(1,numDays+1):
    nextDay = int(input("Day " + str(i) + "'s high temp:"))
    temp.append(nextDay)
    total += nextDay
avg = round(total/numDays,2) 
print("\n average = "+str(avg))

above = 0
for i in temp:
    if i > avg :
        above +=1
print(str(above) + " days(s) above average")        

how many day's temp? 2
Day 1's high temp:233
Day 2's high temp:233

 average = 233.0
0 days(s) above average


In [36]:
#que 1 missing no.


def findMissi(lis,n):
    sum1 = (10*11)/2
    sum2 = sum(lis)
    print(sum1-sum2)

mylist = [1,2,3,4,5,6,7,9]    
findMissi(mylist,9)    

18.0


In [3]:
#que2 two sum
def sumt(num,t):
    for i in range(len(num)):
        for j in range(i+1,len(num)):
            if num[i]==num[j]:
                continue
            elif num[i]+num[j] == t:
                print(i,j)
                

In [2]:
l =[1,2,3,4,5]
sumt(l,5)

0 3
1 2


In [6]:
def buildArray(nums) :
  q = len(nums)
  
  # turn the array into a=qb+r
  for i in range(len(nums)):
    r = nums[i]
    
    # retrieve correct value from potentially already processed element
    # i.e. get r from something maybe already in the form a = qb + r
    # if it isnt already processed (doesnt have qb yet), that's ok b/c
    # r < q, so r % q will return the same value
    b = nums[nums[i]] % q
    
      # put it all together
    nums[i] = q*b + r
    
  # extract just the final b values
  for i in range(len(nums)):
    nums[i] = nums[i] // q
  
  return nums

buildArray([0,2,1,5,3,4])

[0, 1, 2, 4, 5, 3]